language: node_js
node_js:
  - "12"
  - "10"
  - "8"
  - "6"

env:
  - DEBUG=*

script:
  - echo "Running tests against $(node -v)..."
  - npm run test

after_script:
  - npm run coverage
  - cat ./coverage/lcov.info | coveralls

services:
  - mongodb
